// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Unsupported platform for Firebase');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQx7NqFzchvZ23hR63nIT50zvlipI-ABE',
    appId: '1:814529303408:android:7b7d5e1b5b42755e05b5b5',
    messagingSenderId: '814529303408',
    projectId: 'getgas-2e09a',
    storageBucket: 'getgas-2e09a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXYo72s7fgQqoucwU4riGiJRC4Boj9WfI',
    appId: '1:814529303408:web:a8ec5308e0ac680005b5b5',
    messagingSenderId: '814529303408',
    projectId: 'getgas-2e09a',
    authDomain: 'getgas-2e09a.firebaseapp.com',
    storageBucket: 'getgas-2e09a.firebasestorage.app',
    measurementId: 'G-GP48H8G7TZ',
  );
}
