// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Unsupported platform for Firebase');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW7GA8hFgGh7Ht0mpJu_KWivitFTEEOr4',
    appId: '1:757657730993:android:41d3d5ad7b651ccfe24790',
    messagingSenderId: '757657730993',
    projectId: 'get-gas-customer',
    storageBucket: 'get-gas-customer.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDDjTFpoq-HJ-g0-0Q89NRQL8aD5A8v8',
    appId: '1:757657730993:web:a53113c7b1fe2051e24790',
    messagingSenderId: '757657730993',
    projectId: 'get-gas-customer',
    authDomain: 'get-gas-customer.firebaseapp.com',
    storageBucket: 'get-gas-customer.firebasestorage.app',
  );
}
